# Generated by Django 3.2.4 on 2021-06-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convert',
            old_name='path',
            new_name='file',
        ),
    ]
