# Generated by Django 3.2.4 on 2021-06-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_rename_path_convert_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert',
            name='removed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convert',
            name='file',
            field=models.ImageField(upload_to='original/'),
        ),
    ]
