# Generated by Django 3.2.4 on 2021-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_auto_20210628_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
